### ISSUE TITLE
BOT - Aluguel de cavalos share-profit

### ISSUE THREAD

**Issue by future2back** [GabrielZulian/pegaxy-racing-bot#1]
Fala @GabrielZulian , tudo joia irmao?

Voce tem alguma solucao para aluguel de cavalos com share-profit ja que esta muito dificil conseguir alugar?

Obrigado e sucesso irmao!

**Comment by GabrielZulian** [comment]
Opa, estou desenvolvendo um bot para isso, porém é mais complexo e demanda tempo, algo difícil ultimamente. E provavelmente vou precisar monetizar de alguma forma. Mas quando finalizar eu insiro o link no README desse projeto linkando para o outro.

**Comment by GabrielZulian** [comment]
Tranquilo irmão.
Não, este link serve somente para donates. Quando finalizado o projeto para **aluguéis** vou deixar em um título bem explícito explicando sobre.

**Comment by future2back** [comment]
Fala @GabrielZulian tranquilo irmao?  Alguma novidade sobre o desenvolvimento da ferramenta? Voce ta usando quais ferramatas para a solucao? puppeteer?

Abracos.

**Comment by booyxlo** [comment]
pessoal, eu desenvolvi um script que resumidamente permite escolha de porcentagens e quantidade de cavalos que você quer alugar.. além de suporte pros q possuem dificuldade, quem precisar só mandar msg. abcs
